

GET http://localhost:4000/api/v1/health-check


###
POST http://localhost:4000/health-check
x-api-key: GCMUDiuY5a7WvyUNt9n3QztToSHzK7Uj
Content-Type: application/json
Authorization: Bearer <your_token_received_from_signup_or_login>

{
    "userName": "user1",
    "password": "pass"
}
###

POST http://localhost:4000/login/
Content-Type: application/json

{
    "userName": "user1",
    "password": "pass"
}
###